version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum install -y maven

  build:
    commands:
      - echo Building the Java application...
      - mvn clean package
      - chmod +x scripts/*.sh
      - mkdir -p output
      - cp appspec.yml output/
      - cp -r scripts output/
      - cp target/*.jar output/

artifacts:
  base-directory: output
  files:
    - '**/*'
